//! Emit JSON Schema for the kernel boundary types.
//! Usage: cargo run --example gen_schema --features schema-gen
use schemars::schema_for;
use schemars::schema::RootSchema;
use std::fs;

/// Stamp a `$comment` provenance marker as the first line inside the
/// schema's root object. Splices the pretty-printed string directly rather
/// than round-tripping through `serde_json::Value` (whose `Map` is a
/// `BTreeMap` here — no `preserve_order` feature — which would alphabetize
/// every key and blow up the diff to a full-file rewrite).
fn to_marked_json(schema: &RootSchema) -> String {
    let pretty = serde_json::to_string_pretty(schema).unwrap();
    let comment = serde_json::to_string(
        "Generated by cargo run --example gen_schema --features schema-gen. DO NOT EDIT.",
    )
    .unwrap();
    let after_brace = pretty.find('\n').unwrap() + 1;
    format!("{}  \"$comment\": {comment},\n{}", &pretty[..after_brace], &pretty[after_brace..])
}

/// Mirrors the ad-hoc JSON built by `drivers::wire::merge_field_impl`
/// (`{"kind":"Resolved","value":...}` / `{"kind":"Conflict","reason":...}`).
/// No runtime type carries this shape — it's assembled inline with
/// `serde_json::json!` — so this schema-only enum stands in for it.
#[derive(schemars::JsonSchema)]
#[serde(tag = "kind")]
#[allow(dead_code)]
enum MergeOutcomeWire {
    Resolved { value: serde_json::Value },
    Conflict { reason: String },
}

fn main() {
    // spec/ lives at the repo root, one level above this crate (src/).
    // Anchor on CARGO_MANIFEST_DIR so the paths survive any invocation CWD.
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../spec/schema");
    fs::create_dir_all(dir).unwrap();

    fs::write(
        format!("{dir}/wire-changelog.schema.json"),
        to_marked_json(&diff_fusion::drivers::wire::wire_changelog_schema()),
    )
    .unwrap();

    fs::write(
        format!("{dir}/policy-config.schema.json"),
        to_marked_json(&schema_for!(
            diff_fusion::application::policy::declaration::MergePolicyRef
        )),
    )
    .unwrap();

    fs::write(
        format!("{dir}/merge-outcome.schema.json"),
        to_marked_json(&schema_for!(MergeOutcomeWire)),
    )
    .unwrap();

    fs::write(
        format!("{dir}/policy-document.schema.json"),
        to_marked_json(&schema_for!(
            diff_fusion::application::policy::declaration::PolicyDocument
        )),
    )
    .unwrap();

    println!("wrote spec/schema/");
}
