// Generates cross-language kernel test vectors for `three_way_diff` and
// `merge_field` — the two kernel functions with no cross-runtime fixtures
// yet (existing vectors cover only `idempotency_key_hex` + `canonical_json`).
//
// Run:
//   cargo run --example gen_kernel_vectors > ../spec/vectors/kernel-vectors.json
//
// The TS and Go ports read the resulting JSON and replay each vector through
// their own wire-boundary implementation, asserting exact string equality.
//
// # Wire boundary, not domain
//
// Vectors are generated by calling `drivers::wire::three_way_diff_impl` /
// `merge_field_impl` directly — the actual string-in/string-out boundary the
// TS and Go runtimes cross — not the domain layer. This captures the
// `WireFieldChange` re-encoding (absent key = unchanged, present `null` =
// cleared) that a domain-level fixture would miss entirely.
//
// # Envelope
//
// `wire.rs` returns a bare `Result<String, String>`; the `{"ok"/"err"}`
// envelope is applied one layer up, in `drivers/wasip1.rs`'s `envelope()`.
// So `expected` here holds the bare success/error string, with a sibling
// `isErr` boolean telling each runtime which arm to assert.
//
// All inputs/outputs are stored as JSON-encoded STRINGS, never parsed
// objects — byte-identical input crosses to every runtime unreshaped by any
// runtime's own serializer.

use diff_fusion::drivers::wire::{
    compare_json_impl, merge_field_impl, three_way_diff_impl, transform_to_cif_impl,
};
use serde_json::{json, Value};

fn transform_entry(name: &str, source: &str, schema: &str, format_id: &str) -> Value {
    let (expected, is_err) = match transform_to_cif_impl(source, schema, format_id) {
        Ok(s) => (s, false),
        Err(e) => (e, true),
    };
    json!({
        "name": name,
        "source": source,
        "schema": schema,
        "formatId": format_id,
        "expected": expected,
        "isErr": is_err,
    })
}

fn compare_entry(name: &str, a: &str, b: &str) -> Value {
    let (expected, is_err) = match compare_json_impl(a, b) {
        Ok(s) => (s, false),
        Err(e) => (e, true),
    };
    json!({
        "name": name,
        "a": a,
        "b": b,
        "expected": expected,
        "isErr": is_err,
    })
}

fn three_way_entry(name: &str, ancestor: &str, a: &str, b: &str) -> Value {
    let (expected, is_err) = match three_way_diff_impl(ancestor, a, b) {
        Ok(s) => (s, false),
        Err(e) => (e, true),
    };
    json!({
        "name": name,
        "ancestor": ancestor,
        "a": a,
        "b": b,
        "expected": expected,
        "isErr": is_err,
    })
}

fn merge_field_entry(name: &str, change: &str, policy_ref: &str, ctx: &str) -> Value {
    let (expected, is_err) = match merge_field_impl(change, policy_ref, ctx) {
        Ok(s) => (s, false),
        Err(e) => (e, true),
    };
    json!({
        "name": name,
        "change": change,
        "policyRef": policy_ref,
        "ctx": ctx,
        "expected": expected,
        "isErr": is_err,
    })
}

fn main() {
    let three_way_diff = vec![
        // ─── Basics ────────────────────────────────────────────────────────
        three_way_entry(
            "no-change",
            r#"{"price":10,"qty":5}"#,
            r#"{"price":10,"qty":5}"#,
            r#"{"price":10,"qty":5}"#,
        ),
        three_way_entry("a-only-change", r#"{"price":10}"#, r#"{"price":12}"#, r#"{"price":10}"#),
        three_way_entry("b-only-change", r#"{"price":10}"#, r#"{"price":10}"#, r#"{"price":15}"#),
        three_way_entry(
            "both-sides-agree",
            r#"{"price":10}"#,
            r#"{"price":12}"#,
            r#"{"price":12}"#,
        ),
        three_way_entry(
            "both-sides-conflict",
            r#"{"price":10}"#,
            r#"{"price":12}"#,
            r#"{"price":15}"#,
        ),

        // ─── Null-clear vs key-absent ──────────────────────────────────────
        // Highest-value pair: wire distinguishes "A cleared the field to
        // null" (present key, `null` value) from "A didn't touch it" (key
        // absent entirely). The two vectors below independently produce the
        // SAME wire output — deleting a key from the document reads
        // identically to setting it to `null` at this layer (compare_json's
        // `unwrap_or(&Value::Null)` for missing keys), which is itself worth
        // pinning as a cross-runtime gotcha.
        three_way_entry(
            "null-clear-explicit",
            r#"{"status":"draft","other":"x"}"#,
            r#"{"status":null,"other":"x"}"#,
            r#"{"status":"draft","other":"x"}"#,
        ),
        three_way_entry(
            "null-clear-via-key-deletion",
            r#"{"status":"draft","other":"x"}"#,
            r#"{"other":"x"}"#,
            r#"{"status":"draft","other":"x"}"#,
        ),

        // ─── Nested paths ──────────────────────────────────────────────────
        three_way_entry(
            "nested-object-path",
            r#"{"pricing":{"amount":10,"currency":"usd"}}"#,
            r#"{"pricing":{"amount":12,"currency":"usd"}}"#,
            r#"{"pricing":{"amount":10,"currency":"usd"}}"#,
        ),
        three_way_entry(
            "deep-nested-path",
            r#"{"a":{"b":{"c":1}}}"#,
            r#"{"a":{"b":{"c":2}}}"#,
            r#"{"a":{"b":{"c":1}}}"#,
        ),

        // ─── Array values ──────────────────────────────────────────────────
        // Arrays are leaf values to compare_json (not recursed into) — a
        // single-element change replaces the whole array.
        three_way_entry(
            "array-value-replacement",
            r#"{"tags":["a","b"]}"#,
            r#"{"tags":["a","c"]}"#,
            r#"{"tags":["a","b"]}"#,
        ),

        // ─── Empty ancestor / unicode ───────────────────────────────────────
        three_way_entry("empty-ancestor", r#"{}"#, r#"{"new_field":"x"}"#, r#"{}"#),
        three_way_entry(
            "unicode-keys-and-values",
            r#"{"名前":"太郎"}"#,
            r#"{"名前":"次郎"}"#,
            r#"{"名前":"太郎"}"#,
        ),

        // ─── Multiple fields, mixed sources ─────────────────────────────────
        // "c" is untouched by both sides — it must not appear in `changes`
        // at all, not even as an empty/null entry.
        three_way_entry(
            "multi-field-mixed-sources-untouched-field-omitted",
            r#"{"a":1,"b":2,"c":3}"#,
            r#"{"a":10,"b":2,"c":3}"#,
            r#"{"a":1,"b":20,"c":3}"#,
        ),

        // ─── Errors ────────────────────────────────────────────────────────
        three_way_entry("malformed-ancestor-json", "{bad", "{}", "{}"),
        three_way_entry("malformed-a-json", "{}", "{bad", "{}"),
        three_way_entry("malformed-b-json", "{}", "{}", "{bad"),
    ];

    let merge_field = vec![
        // ─── OwnedBy ───────────────────────────────────────────────────────
        merge_field_entry(
            "owned-by-owner-a-wins",
            r#"{"path":"price","old_value":10,"new_from_a":15,"source":"a"}"#,
            r#"{"kind":"owned_by","system":"netsuite"}"#,
            r#"{"system_a":"netsuite","system_b":"shopify"}"#,
        ),
        merge_field_entry(
            "owned-by-non-owner-reverts",
            r#"{"path":"price","old_value":1,"new_from_b":99,"source":"b"}"#,
            r#"{"kind":"owned_by","system":"netsuite"}"#,
            r#"{"system_a":"netsuite","system_b":"shopify"}"#,
        ),
        merge_field_entry(
            "owned-by-unknown-system-conflict",
            r#"{"path":"price","old_value":1,"new_from_a":2,"source":"a"}"#,
            r#"{"kind":"owned_by","system":"unknown_system"}"#,
            r#"{"system_a":"netsuite","system_b":"shopify"}"#,
        ),
        merge_field_entry(
            "owned-by-null-clear-resolves",
            r#"{"path":"status","old_value":"draft","new_from_a":null,"source":"a"}"#,
            r#"{"kind":"owned_by","system":"x"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),

        // ─── Additive ──────────────────────────────────────────────────────
        merge_field_entry(
            "additive-both-sides-accumulate",
            r#"{"path":"qty","old_value":10,"new_from_a":13,"new_from_b":12,"source":"both"}"#,
            r#"{"kind":"additive"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "additive-non-numeric-side-conflict",
            r#"{"path":"qty","old_value":10,"new_from_a":"eleven","source":"a"}"#,
            r#"{"kind":"additive"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),

        // ─── Append ────────────────────────────────────────────────────────
        merge_field_entry(
            "append-both-sides-concatenate",
            r#"{"path":"notes","old_value":["x"],"new_from_a":["x","y"],"new_from_b":["x","z"],"source":"both"}"#,
            r#"{"kind":"append"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "append-non-array-conflict",
            r#"{"path":"notes","old_value":"text","new_from_a":"text plus","source":"a"}"#,
            r#"{"kind":"append"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),

        // ─── StateMachine ──────────────────────────────────────────────────
        merge_field_entry(
            "state-machine-legal-transition",
            r#"{"path":"status","old_value":"draft","new_from_a":"open","source":"a"}"#,
            r#"{"kind":"state_machine","transitions":[{"from":"draft","to":"open"}]}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "state-machine-illegal-transition",
            r#"{"path":"status","old_value":"closed","new_from_a":"draft","source":"a"}"#,
            r#"{"kind":"state_machine","transitions":[{"from":"draft","to":"open"}]}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "state-machine-divergent-transitions-conflict",
            r#"{"path":"status","old_value":"open","new_from_a":"closed","new_from_b":"cancelled","source":"both"}"#,
            r#"{"kind":"state_machine","transitions":[{"from":"open","to":"closed"},{"from":"open","to":"cancelled"}]}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),

        // ─── LastWriteWins ─────────────────────────────────────────────────
        merge_field_entry(
            "last-write-wins-newer-timestamp-wins",
            r#"{"path":"x","old_value":1,"new_from_a":2,"new_from_b":3,"source":"both"}"#,
            r#"{"kind":"last_write_wins","reason":"no natural owner","timestamp_a":200,"timestamp_b":100}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "last-write-wins-tied-timestamps-conflict",
            r#"{"path":"x","old_value":1,"new_from_a":2,"new_from_b":3,"source":"both"}"#,
            r#"{"kind":"last_write_wins","reason":"tie test","timestamp_a":100,"timestamp_b":100}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "last-write-wins-single-side-trivial",
            r#"{"path":"x","old_value":1,"new_from_a":7,"source":"a"}"#,
            r#"{"kind":"last_write_wins","reason":"legacy","timestamp_a":0,"timestamp_b":0}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),

        // ─── SetByKey ──────────────────────────────────────────────────────
        // The minimal constructor (identity + both anchors) defaults
        // on_both_changed to Escalate — so "both changed" conflicts unless
        // a vector below opts into a wider knob.
        merge_field_entry(
            "set-by-key-additions-both-sides-merge",
            r#"{"path":"items","old_value":[{"sku":"x","q":1}],"new_from_a":[{"sku":"x","q":1},{"sku":"y","q":2}],"new_from_b":[{"sku":"x","q":1},{"sku":"z","q":3}],"source":"both"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"sku","b_anchor":"sku"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "set-by-key-both-changed-conflict",
            r#"{"path":"items","old_value":[{"sku":"x","q":1}],"new_from_a":[{"sku":"x","q":10}],"new_from_b":[{"sku":"x","q":20}],"source":"both"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"sku","b_anchor":"sku"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        // Characteristic edge case: A renamed the identity field ("old" ->
        // "new") on the row anchored by stable id=1. Anchor rehoming
        // matches it to its former self instead of reading as a divergent
        // remove+add.
        merge_field_entry(
            "set-by-key-anchor-rehomes-renamed-identity",
            r#"{"path":"items","old_value":[{"sku":"old","id":1,"q":5}],"new_from_a":[{"sku":"new","id":1,"q":5}],"new_from_b":[{"sku":"old","id":1,"q":5}],"source":"a"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"id","b_anchor":"id"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),

        // ─── SetByKey: widened wire knobs ───────────────────────────────────
        // Both changed, Union: shallow-merge the two elements' fields.
        merge_field_entry(
            "set-by-key-on-both-changed-union-merges-fields",
            r#"{"path":"items","old_value":[{"sku":"x","q":1}],"new_from_a":[{"sku":"x","q":1,"a_extra":true}],"new_from_b":[{"sku":"x","q":1,"b_extra":42}],"source":"both"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"sku","b_anchor":"sku","on_both_changed":"Union"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        // Both changed, Union with a nested keyed sub-array: the matched
        // parent's "items" field is itself reconciled by composite key
        // rather than shallow-overlaid.
        merge_field_entry(
            "set-by-key-on-both-changed-union-with-nested-merges-recursively",
            r#"{"path":"groups","old_value":[{"gid":"G1","items":[{"sku":"A","q":1}]}],"new_from_a":[{"gid":"G1","items":[{"sku":"A","q":1},{"sku":"B","q":2}]}],"new_from_b":[{"gid":"G1","items":[{"sku":"A","q":1},{"sku":"C","q":3}]}],"source":"both"}"#,
            r#"{"kind":"set_by_key","identity":["gid"],"a_anchor":"gid","b_anchor":"gid","on_both_changed":"Union","nested":{"items":{"identity":["sku"],"a_anchor":"sku","b_anchor":"sku"}}}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        // Both changed, PreferA: A's element wins outright, no union.
        merge_field_entry(
            "set-by-key-on-both-changed-prefer-a-wins",
            r#"{"path":"items","old_value":[{"sku":"x","q":1}],"new_from_a":[{"sku":"x","q":10}],"new_from_b":[{"sku":"x","q":20}],"source":"both"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"sku","b_anchor":"sku","on_both_changed":"PreferA"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        // Both changed, PreferB: B's element wins outright.
        merge_field_entry(
            "set-by-key-on-both-changed-prefer-b-wins",
            r#"{"path":"items","old_value":[{"sku":"x","q":1}],"new_from_a":[{"sku":"x","q":10}],"new_from_b":[{"sku":"x","q":20}],"source":"both"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"sku","b_anchor":"sku","on_both_changed":"PreferB"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        // Added in A only, on_added_in_a: Exclude — A's new row is dropped
        // instead of the (Include) default of keeping it.
        merge_field_entry(
            "set-by-key-on-added-in-a-exclude-drops-addition",
            r#"{"path":"items","old_value":[{"sku":"x"}],"new_from_a":[{"sku":"x"},{"sku":"y"}],"source":"a"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"sku","b_anchor":"sku","on_added_in_a":"Exclude"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        // Removed in A while B changed it, on_removed_in_a: Remove — the row
        // is dropped without escalating, unlike the (EscalateIfChanged)
        // default.
        merge_field_entry(
            "set-by-key-on-removed-in-a-remove-drops-without-escalating",
            r#"{"path":"items","old_value":[{"sku":"x","q":1}],"new_from_a":[],"new_from_b":[{"sku":"x","q":99}],"source":"both"}"#,
            r#"{"kind":"set_by_key","identity":["sku"],"a_anchor":"sku","b_anchor":"sku","on_removed_in_a":"Remove"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),

        // ─── Errors: malformed JSON ────────────────────────────────────────
        merge_field_entry(
            "malformed-change-json",
            "{bad",
            r#"{"kind":"additive"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "malformed-policy-ref-json",
            r#"{"path":"x","old_value":1,"new_from_a":2,"source":"a"}"#,
            "{bad",
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "malformed-ctx-json",
            r#"{"path":"x","old_value":1,"new_from_a":2,"source":"a"}"#,
            r#"{"kind":"additive"}"#,
            "{bad",
        ),

        // ─── Errors: inconsistent source/presence ───────────────────────────
        merge_field_entry(
            "inconsistent-source-a-with-absent-new-from-a",
            r#"{"path":"s","old_value":"draft","new_from_b":"open","source":"a"}"#,
            r#"{"kind":"state_machine","transitions":[{"from":"draft","to":"open"}]}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "inconsistent-source-b-with-absent-new-from-b",
            r#"{"path":"s","old_value":"draft","new_from_a":"open","source":"b"}"#,
            r#"{"kind":"state_machine","transitions":[{"from":"draft","to":"open"}]}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
        merge_field_entry(
            "inconsistent-source-both-with-absent-new-from-b",
            r#"{"path":"qty","old_value":1,"new_from_a":3,"source":"both"}"#,
            r#"{"kind":"additive"}"#,
            r#"{"system_a":"x","system_b":"y"}"#,
        ),
    ];

    let compare_json = vec![
        // ─── Basics ────────────────────────────────────────────────────────
        compare_entry("no-change", r#"{"price":10,"qty":5}"#, r#"{"price":10,"qty":5}"#),
        compare_entry("scalar-mismatch", r#""x""#, r#""y""#),

        // ─── Multi-key sorted order ────────────────────────────────────────
        // Deterministic BTreeSet iteration (fixes the HashSet nondeterminism
        // bug): paths must come back in sorted order "a","m","z", not
        // insertion order "z","a","m".
        compare_entry(
            "multi-key-sorted-order",
            r#"{"z":1,"a":1,"m":1}"#,
            r#"{"z":2,"a":2,"m":2}"#,
        ),

        // ─── Nested paths ──────────────────────────────────────────────────
        compare_entry(
            "nested-object-path",
            r#"{"pricing":{"amount":10,"currency":"usd"}}"#,
            r#"{"pricing":{"amount":12,"currency":"usd"}}"#,
        ),

        // ─── Missing key treated as null on the missing side ──────────────
        compare_entry("missing-key-treated-as-null", r#"{"keep":1,"gone":"x"}"#, r#"{"keep":1,"added":"y"}"#),

        // ─── Array values ──────────────────────────────────────────────────
        // Arrays are leaf values (not recursed into) — a single-element
        // change replaces the whole array at its enclosing path.
        compare_entry("array-value-replacement", r#"{"tags":["a","b"]}"#, r#"{"tags":["a","c"]}"#),

        // ─── Errors ────────────────────────────────────────────────────────
        compare_entry("malformed-a-json", "{bad", "{}"),
        compare_entry("malformed-b-json", "{}", "{bad"),
    ];

    let transform_to_cif = vec![
        // ─── Basics ────────────────────────────────────────────────────────
        transform_entry(
            "scalar-mapping",
            r#"{"name":"Widget","price":19.99}"#,
            r#"{"cif_schema":{"product_name":{"type":"string","required":true},"product_price":{"type":"number","required":true}},"transformations":{"format_a":{"product_name":{"source_path":"name","type":"string"},"product_price":{"source_path":"price","type":"number"}}}}"#,
            "format_a",
        ),
        transform_entry(
            "nested-dotted-source-path",
            r#"{"product":{"details":{"name":"Gadget"}},"pricing":{"amount":99.99}}"#,
            r#"{"cif_schema":{"product_name":{"type":"string","required":true},"product_price":{"type":"number","required":true}},"transformations":{"nested_format":{"product_name":{"source_path":"product.details.name","type":"string"},"product_price":{"source_path":"pricing.amount","type":"number"}}}}"#,
            "nested_format",
        ),
        transform_entry(
            "type-conversion",
            r#"{"id":"12345","active":"true","quantity":"100"}"#,
            r#"{"cif_schema":{"product_id":{"type":"string","required":true},"is_active":{"type":"boolean","required":true},"stock":{"type":"number","required":true}},"transformations":{"format_b":{"product_id":{"source_path":"id","type":"string"},"is_active":{"source_path":"active","type":"boolean"},"stock":{"source_path":"quantity","type":"number"}}}}"#,
            "format_b",
        ),

        // ─── Array elements ────────────────────────────────────────────────
        transform_entry(
            "array-elements-with-anchors",
            r#"{"lineItems":[{"extId":"A-1","sku":"SKU-X","quantity":3},{"extId":"A-2","sku":"SKU-Y","quantity":5}]}"#,
            r#"{"cif_schema":{"items":{"type":"array","required":true,"element":{"externalId":{"type":"string","anchor":"a"},"internalId":{"type":"string","anchor":"b"},"sku":{"type":"string","required":true},"qty":{"type":"number"}}}},"transformations":{"erp":{"items":{"source_path":"lineItems","type":"array","element":{"externalId":{"source_path":"extId","type":"string"},"sku":{"source_path":"sku","type":"string"},"qty":{"source_path":"quantity","type":"number"}}}}}}"#,
            "erp",
        ),
        transform_entry(
            "array-element-required-field-missing",
            r#"{"lineItems":[{"sku":"SKU-X"},{}]}"#,
            r#"{"cif_schema":{"items":{"type":"array","element":{"sku":{"type":"string","required":true}}}},"transformations":{"erp":{"items":{"source_path":"lineItems","type":"array","element":{"sku":{"source_path":"sku","type":"string"}}}}}}"#,
            "erp",
        ),

        // ─── Object children — the feature this vector set exists to pin
        // down: exercises `Transformer::transform_element`'s "children" kind.
        transform_entry(
            "object-children-nested-cif-object",
            r#"{"vendor":{"companyName":"Acme","contact":{"email":"a@acme.io"}}}"#,
            r#"{"cif_schema":{"supplier":{"type":"object","required":true,"children":{"name":{"type":"string","required":true},"email":{"type":"string"}}}},"transformations":{"f":{"supplier":{"source_path":"vendor","type":"object","children":{"name":{"source_path":"companyName","type":"string"},"email":{"source_path":"contact.email","type":"string"}}}}}}"#,
            "f",
        ),
        transform_entry(
            "required-object-child-missing",
            r#"{"vendor":{}}"#,
            r#"{"cif_schema":{"supplier":{"type":"object","children":{"name":{"type":"string","required":true}}}},"transformations":{"f":{"supplier":{"source_path":"vendor","type":"object","children":{"name":{"source_path":"companyName","type":"string"}}}}}}"#,
            "f",
        ),
        transform_entry(
            "top-level-source-path-dot",
            r#"{"id":"42","other":true}"#,
            r#"{"cif_schema":{"net_suite":{"type":"object","children":{"id":{"type":"string"}}}},"transformations":{"f":{"net_suite":{"source_path":".","type":"object","children":{"id":{"source_path":"id","type":"string"}}}}}}"#,
            "f",
        ),
        transform_entry(
            "object-child-source-path-dot",
            r#"{"tag":"urgent"}"#,
            r#"{"cif_schema":{"meta":{"type":"object","children":{"raw":{"type":"string"}}}},"transformations":{"f":{"meta":{"source_path":"tag","type":"object","children":{"raw":{"source_path":".","type":"string"}}}}}}"#,
            "f",
        ),
        transform_entry(
            "array-of-objects-with-nested-children-composing",
            r#"{"lines":[{"sku":"X","dims":{"w":2,"h":3}}],"vendor":{"name":"Acme","addrs":[{"city":"Oslo"},{"city":"Bergen"}]}}"#,
            r#"{"cif_schema":{"items":{"type":"array","element":{"sku":{"type":"string"},"dimensions":{"type":"object","children":{"width":{"type":"number"},"height":{"type":"number"}}}}},"supplier":{"type":"object","children":{"name":{"type":"string"},"addresses":{"type":"array","element":{"city":{"type":"string"}}}}}},"transformations":{"f":{"items":{"source_path":"lines","type":"array","element":{"sku":{"source_path":"sku","type":"string"},"dimensions":{"source_path":"dims","type":"object","children":{"width":{"source_path":"w","type":"number"},"height":{"source_path":"h","type":"number"}}}}},"supplier":{"source_path":"vendor","type":"object","children":{"name":{"source_path":"name","type":"string"},"addresses":{"source_path":"addrs","type":"array","element":{"city":{"source_path":"city","type":"string"}}}}}}}}"#,
            "f",
        ),
        transform_entry(
            "nested-arrays-of-objects",
            r#"{"orders":[{"id":"o1","lines":[{"sku":"a"},{"sku":"b"}]},{"id":"o2","lines":[{"sku":"c"}]}]}"#,
            r#"{"cif_schema":{"orders":{"type":"array","element":{"id":{"type":"string"},"lines":{"type":"array","element":{"sku":{"type":"string"}}}}}},"transformations":{"f":{"orders":{"source_path":"orders","type":"array","element":{"id":{"source_path":"id","type":"string"},"lines":{"source_path":"lines","type":"array","element":{"sku":{"source_path":"sku","type":"string"}}}}}}}}"#,
            "f",
        ),

        // ─── Errors ────────────────────────────────────────────────────────
        transform_entry(
            "unknown-format",
            r#"{"name":"Widget"}"#,
            r#"{"cif_schema":{},"transformations":{"format_a":{}}}"#,
            "nonexistent_format",
        ),
        transform_entry(
            "missing-cif-schema",
            r#"{}"#,
            r#"{"transformations":{"f":{}}}"#,
            "f",
        ),
    ];

    let out = json!({
        "threeWayDiff": Value::Array(three_way_diff),
        "mergeField": Value::Array(merge_field),
        "compareJson": Value::Array(compare_json),
        "transformToCif": Value::Array(transform_to_cif),
    });
    println!("{}", serde_json::to_string_pretty(&out).unwrap());
}
