#!/usr/bin/env bash
# Copy root-level docs into the Jekyll site as Reference pages.
# The root files stay the single source of truth; these copies are build
# artifacts (gitignored), regenerated by CI and before local preview.
set -euo pipefail
cd "$(dirname "$0")/.."

out=docs/reference
mkdir -p "$out"

fold() {  # $1=source  $2=slug  $3=title  $4=nav_order
  {
    printf -- '---\n'
    printf -- 'layout: default\n'
    printf -- 'title: %s\n' "$3"
    printf -- 'parent: Reference\n'
    printf -- 'nav_order: %s\n' "$4"
    # ARCHITECTURE.md has `{{"found?"}}` inside a mermaid block; Liquid would
    # eat it. None of these files use Liquid, so switch it off wholesale.
    printf -- 'render_with_liquid: false\n'
    printf -- '---\n\n'
    cat "$1"
  } > "$out/$2.md"
}

fold ARCHITECTURE.md architecture Architecture 1
fold ROADMAP.md      roadmap      Roadmap      2
fold CONTRIBUTING.md contributing Contributing 3
